### ISSUE TITLE
Add async/await support for Promises with Babel

### ISSUE THREAD

**Issue by andrewbrooke** [andrewbrooke/github-lang-getter#5]

**Comment by domfarolino** [comment]
Just so it is clear, async/await and Promises are not different things. Async/await is just a different way to use Promises...turning `.then()` and `catch()` into `try {} catch() {}` which is even more similar to their synchronous counter parts. I'm pretty sure you can get away with this in vanilla nodev7, though I'm not sure so yeah if you wanted to still support older versions of node it is probably best to use babel.

**Comment by andrewbrooke** [comment]
Oh yeah I'm aware, my title is a bit misleading. Node 7.6 brought support for async/await without using `--harmony`, but I'd like to bring support to much older versions so Babel is probably the way to go.

I'm thinking this should aid in the readability of our promise chains in a couple places
